config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/dashboard", to: "pages#dashboard"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/dashboard", to: "pages#dashboard"
  resources :exhibitions, only: [:index, :show, :edit, :update, :destroy] do
    resources :bookings, only: [:index, :new, :create]
    resources :reviews, only: [:new, :create, :destroy]
    resources :favorites, only: [:create]
  end
  resources :favorites, only: [:destroy], as: "favorite_delete"
  resources :users do
    resources :friendships, only: [:new, :create, :index]
    resources :favorites, only: [:index]
  end
  resources :sites, only: [:show, :edit, :update, :destroy]
  get "/fav", to: "favorites#fav", as: "favorite"
  get "/ticket", to: "bookings#ticket", as: "ticket"
end

app/models/exhibition.rb
class Exhibition < ApplicationRecord
  CATEGORIES = ['Peinture', 'Sculpture', 'Street-Art', 'Contemporain', 'Design', 'Photographie', 'Architecture', 'Cinema', 'Histoire', 'Musique']
  belongs_to :site
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  # validates :category, inclusion: { in: CATEGORIES }
  geocoded_by :address
  after_validation :geocode, if: ->(obj) { obj.address_changed? and obj.latitude.blank? }
end

app/controllers/exhibitions_controller.rb
class ExhibitionsController < ApplicationController
  before_action :set_exhibition, only: %i[show destroy update edit]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @exhibitions = nil
    @sites = nil
    @museum = false
    @markers_site = []
    @markers_exhibition = []

    if params[:search].present?

      if params[:search][:museum].present? && params[:search][:museum].include?("1")
        @sites = Site.where(fake: false)
        @museum = true
      end

      @categories = Exhibition::CATEGORIES.select { |category| params[:search][category] == '1' }
      @exhibitions = Exhibition.where(category: @categories).where("ending_date > ?", Date.today)
      if params[:search][:address].present?
        @sites = Site.near(params[:search][:address], 6)
        @museum = true
        @exhibitions = Exhibition.where(site_id: @sites.map(&:id)).where("ending_date > ?", Date.today)
        @categories = Exhibition::CATEGORIES
      end

    elsif params[:category].present?
      @exhibitions = Exhibition.where(category: params[:category]).where("ending_date > ?", Date.today)
      @categories = params[:category]
      @joconde = true
    else
      @exhibitions = Exhibition.all.where("ending_date > ?", Date.today)
      @categories = Exhibition::CATEGORIES
      @sites = Site.where(fake: false)
      @museum = true
      @joconde = true
    end

    set_favorites
    define_markers
  end

  def show
    @review = Review.new
    set_favorite
  end

  def destroy
    @exhibition.destroy
    redirect_to exhibitions_path
  end

  def edit
    @sites = Site.all
  end

  def update
    @site = Site.find(params[:exhibition][:site_id].to_i)
    @exhibition.update(exhibition_params)
    @exhibition.update(site: @site)
    redirect_to exhibition_path(@exhibition)
  end

  private

  def set_exhibition
    @exhibition = Exhibition.find(params[:id])
  end

  def exhibition_params
    params.require(:exhibition).permit(:title, :starting_date, :ending_date, :address, :fake, :description, :price, :category, :photo, :place, :old, :date, site_attributes: [:id])
  end

  def define_markers
    if @sites
      @markers_site = @sites.map do |site|
        {
          lat: site.latitude,
          lng: site.longitude,
          infoWindow: render_to_string(partial: "info_window_site", locals: { site: site }),
          image_url: helpers.asset_url('green-pin.png'),
          category: 'Collection permanente',
          type_expo: 'Collection permanente'
        }
      end
    end

    if @exhibitions
      @markers_exhibition = @exhibitions.map do |exhibition|
        {
          lat: exhibition.latitude,
          lng: exhibition.longitude,
          infoWindow: render_to_string(partial: "info_window_exhibition", locals: { exhibition: exhibition }),
          image_url: helpers.asset_url('pin-exhibitions.png'),
          category: exhibition.category,
          type_expo: 'Collection temporaire'
        }
      end
    end

    @markers = @markers_site + @markers_exhibition
  end

  def set_favorite
    return unless user_signed_in?

    if Favorite.find_by(user: current_user, exhibition: @exhibition)
      @favorite = Favorite.find_by(user: current_user, exhibition: @exhibition)
    else
      @favorite = Favorite.new
    end
  end

  def set_favorites
    @favorites = current_user.favorites if user_signed_in?
  end
end

app/views/exhibitions/_favorite_icon.html.erb
<% if @favorites.find_by(exhibition: exhibition) %>
  <%= link_to favorite_path(exhibition_id: exhibition.id), remote: true do %>
  <i class="fas fa-heart"></i>
  <% end %>
<% else %>
  <%= link_to favorite_path(exhibition_id: exhibition.id), remote: true do %>
    <i class="far fa-heart"></i>
  <% end %>
<% end %>

app/views/exhibitions/_form.html.erb
<%= @exhibition.title %>
<%= @exhibition.description %>
<%= simple_form_for @exhibition do |f| %>
  <%= f.input :place, input_html: {class: "edit-form"} %>
  <%= f.association :site, collection: @sites.order(:name), value_method: :id, label: "Site" , input_html: {class: "edit-form"}   %>
  <%= f.input :category, label: "category - A CHANGER", collection: Exhibition::CATEGORIES, input_html: {class: "edit-form"} %>
  <%= f.input :address, label: "addresse - A checker", input_html: {class: "edit-form"} %>
  <%= f.submit "Edit exhibition", class: "btn btn-success" %>
<% end %>

app/views/exhibitions/_info_window_exhibition.html.erb
<%= link_to exhibition_path(exhibition) do %>
  <div class="info-window-card">
    <div class="info-window-img-top">
      <%= image_tag exhibition.photo, class:"info-window-img-top" %>
      <p class= "<%= exhibition.category %>" ><%= exhibition.category%></p>
    </div>
    <div class="info-window-title">
        <p><%= exhibition.title %></p>
    </div>
    <div class="info-window-body">
      <div>
        <p><i class="fas fa-map-marker-alt pr-1"></i><%= exhibition.place %>
          <br>
          Date de fin : <%= exhibition.ending_date.strftime('%d/%m/%Y') %>
        </p>
      </div>
      <div class="info-window-link">
        <% if user_signed_in? %>
          <div id="favorite-icon" class="favorite-icon-index">
            <%= render "favorite_icon", exhibition: exhibition %>
          </div>
        <% end %>
        <!-- <i class="far fa-heart favorite-icon"></i> -->
      </div>
    </div>
  </div>
<% end %>

app/views/exhibitions/_info_window_site.html.erb
<%= link_to site_path(site) do %>
  <div class="info-window-card">
    <div class="info-window-img-top">
      <% if site.picture %>
        <%= image_tag site.picture, class:"info-window-img-top" %>
      <% else %>
        <%= image_tag "placeholder-museum-min.png", alt: "alttext", class:"info-window-img-top" %>
      <% end %>
    </div>
    <div class="info-window-title">
        <p><%= site.name %></p>
    </div>
    <div class="info-window-body">
      <div>
        <p><i class="fas fa-map-marker-alt pr-1"></i><%= site.address %>
          <br>
          Collection permanente
        </p>
      </div>
      <div class="info-window-link">
        <i class="far fa-heart favorite-icon-index"></i>
      </div>
    </div>
  </div>
<% end %>

app/views/exhibitions/edit.html.erb
<h1>Editing Exhibition</h1>
<div class="container">
<%= render 'form', exhibition: @exhibition %>

<%= link_to 'Show', @exhibition %> |
<%= link_to 'Back', exhibitions_path %> |
<%= link_to "Delete", exhibition_path(@exhibition), method: :delete, data: { confirm: "Are you sure?" }  %>
</div>

app/views/exhibitions/index.html.erb
<div class="container-map", style="width: 100vw; top: 0; bottom: 0; position: absolute; display: grid; box-sizing: border-box;">
  <div id="map"
       style="visibility: hidden"
       data-markers="<%= @markers.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
  <div class="wrapper-rubik" id = "loader">
    <% if @joconde %>
      <div class="rubik-loader">
        <h4 class = 'loading '>Une petite joconde...</h4>
      </div>
    <% end %>
  </div>
</div>

<!-- Button trigger modal -->
<button type="button" id ='filter-button' data-toggle="modal" data-target="#exampleModalCenter">
  <%= image_tag "filter-colored-reverse.png", alt: "filter", id: 'filter' %>
</button>

<%= render 'shared/filter-modal' %>

<!--   <div id="static"></div> -->

app/views/exhibitions/show.html.erb
<div class="description-show-exhibition">
  <%= image_tag @exhibition.photo, alt: @exhibition.description, class: "img-exhibition-description" %>
  <%= link_to :back do %>
    <p class= "arrow-back-link"><i class="fas fa-arrow-circle-left"></i></p>
  <% end %>
  <p class= "<%= @exhibition.category %> show-category-tag" ><%= @exhibition.category%></p>
</div>

<div class="container show-description-container">
  <h4>  <%= @exhibition.title %> </h4>
  <% if user_signed_in? %>
    <div class="favorite-icon-show">
      <% if @favorite.user == current_user %>
        <%= link_to favorite_path(exhibition_id: @exhibition.id) do %>
        <i class="fas fa-heart"></i>
        <% end %>
      <% else %>
        <%= link_to favorite_path(exhibition_id: @exhibition.id) do %>
          <i class="far fa-heart"></i>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>


<div class="container">
  <div class="museum-description-box">
    <% if @exhibition.site.picture %>
        <%= image_tag @exhibition.site.picture, class:"museum-picture-description" %>
      <% else %>
        <%= image_tag "placeholder-museum.jpg", alt: "alttext", class:"museum-picture-description" %>
      <% end %>
    <div>
      <p> <%= @exhibition.place %> </p>
      <p id="adress-grey-museum"> <%= @exhibition.address %> </p>
    </div>
  </div>
  <div>
    <% if user_signed_in? && current_user.admin  %>
      <%= link_to 'EDIT', edit_exhibition_path(@exhibition)  %>
    <% end %>
  </div>

  <div class="description-exhibition-show">
    <p><strong>Description :</strong>
    <br>
    <%= @exhibition.detailed_desc %><br>
    <em>
    <% if @exhibition.starting_date && @exhibition.ending_date %>
      Du <%= @exhibition.starting_date.strftime('%d/%m/%Y') %> au <%= @exhibition.ending_date.strftime('%d/%m/%Y') %>
    <% elsif @exhibition.date %>
      <%= @exhibition.date %>
    <% end %>
    </em></p>
  </div>
  <%= link_to "Site Internet de l'évènement", @exhibition.link, class:"btn-res-museum-around buttons-show-exhibition" %>
</div>


<div class="container review-card-show">
  <div>
    <h5 class="review-title text-center pt-3">Vous avez aimé ? <br> Faites-le nous savoir !</h5>
  </div>
  <div class="px-4 white-background-show">
    <!-- <p>Vous avez aimé ? Faites-le nous savoir !</p> -->
    <%= simple_form_for [ @exhibition, @review ] do |f| %>
      <%= f.input :rating, collection: (1..5).to_a, label: false %>
      <%= f.input :comment, label: false %>
      <%= f.submit "Valider", class: "btn-museum-around btn-avis" %>
    <% end %>
  </div>
  <div>
    <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
    <ul class="list-group">
      <% @exhibition.reviews.each do |review| %>
        <li class="list-group-item posted-reviews-show">
        <% review.rating.to_i.times do  %>
          <i class="fas fa-star"></i>
        <% end %>
        <% (5-review.rating.to_i).times do  %>
          <i class="far fa-star"></i>
        <% end %>
        <strong><%= review.user.first_name %>
        <% if review.user.last_name %>
          <%= review.user.last_name[0] %>
        <% end %>
        .</strong> - <%= review.comment %>
        </li>
      <% end %>
    </ul>
  </div>
</div>