config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/dashboard", to: "pages#dashboard"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/dashboard", to: "pages#dashboard"
  resources :exhibitions, only: [:index, :show, :edit, :update, :destroy] do
    resources :bookings, only: [:index, :new, :create]
    resources :reviews, only: [:new, :create, :destroy]
    resources :favorites, only: [:create]
  end
  resources :favorites, only: [:destroy], as: "favorite_delete"
  resources :users do
    resources :friendships, only: [:new, :create, :index]
    resources :favorites, only: [:index]
  end
  resources :sites, only: [:show, :edit, :update, :destroy]
  get "/fav", to: "favorites#fav", as: "favorite"
  get "/ticket", to: "bookings#ticket", as: "ticket"
end

app/views/shared/_filter-modal.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
<!--       <div class="modal-header py-2">
        <h6 class="modal-title" id="exampleModalLongTitle">Filtrer</h6>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div> -->
      <div class="modal-body">
        <h5><strong>Mes filtres</strong></h5>
        <%= simple_form_for :search, url: exhibitions_path, method: :get, class: "form-inline" do |f| %>
          <%= f.input :museum, as: :boolean, input_html: {checked: @museum, class: "toggle toggle-green" }, label: "Collections permanentes" %>
          <h6 class = 'subtitle-form'><strong>Collections temporaires - catégories</strong></h6>
          <% Exhibition::CATEGORIES.each do |category| %>
            <%= f.input category, as: :boolean, input_html: {checked: @categories.include?(category), class: "toggle toggle-yellow" } %>
          <% end %>
          <%= f.button :submit, 'Découvrir !', class: 'btn-res-museum-around-modal' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class= "navbar-down-screen border-top py-2">

  <%= link_to root_path do %>
    <i class="fas fa-home <%= current_page?(root_path) ? "" : "icon-not-active"  %>"></i>
  <% end %>

  <%= link_to exhibitions_path do %>
    <i class="fas fa-search-location <%= current_page?(exhibitions_path) ? "" : "icon-not-active" %>"></i>
  <% end %>

  <% if user_signed_in? %>
    <%= link_to user_favorites_path(current_user) do %>
      <i class="fas fa-heart <%= current_page?(user_favorites_path(current_user)) ? "" : "icon-not-active" %>"></i>
    <% end %>
  <% end %>
  <% if user_signed_in? && current_user.photo.attached? %>
    <%= link_to dashboard_path do %>
      <div class= "profile-pic <%= current_page?(dashboard_path(current_user)) ? "" : "icon-not-active"  %>">
        <%= cl_image_tag current_user.photo.key, crop:'crop' %>
      </div>
    <% end %>
  <% else %>
    <%= link_to dashboard_path do %>
      <div class="icon-user <%= current_page?(dashboard_path(current_user)) ? "" : "icon-not-active" %>">
        <i class="far fa-user-circle"></i>
      </div>
    <% end %>
  <% end %>
</div>

<!-- gravity:'face', crop:'crop' -->

app/views/shared/_ticket-modal.html.erb
<!-- Modal -->
<!-- <div class="banner-home-page"> -->
  <div class="modal fade" id="ticketModal<%= i %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">

       <!--  <div class="modal-header py-2">
          <h6 class="modal-title" id="exampleModalLongTitle">Filtrer</h6> -->
          <div class="cross-modal-dash">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
      <!--   </div> -->
        <div class="modal-body ticket-confirm">
          <div class="banner-top expo-reservation">
            <div class="logo-museum-dashboard">
             <%= image_tag("logo-museum-around-darker.png", class: "logo-img") %>
            </div>
          </div>
          <div class="nom-expo-dash">
            <strong> <%= @booking.exhibition.title%> </strong>
            <hr>
          </div>
          <div class="date-heure-expo-dash">
          Le <strong> <%= @booking.date.strftime('%d/%m/%Y')%> </strong>à <strong> <%= @booking.time.strftime('%H:%M') %> </strong>
          <hr>
          </div>
          <div class="nb-visit-expo">
          Pour <strong> <%= @booking.number_of_tickets%> </strong>
            <% if @booking.number_of_tickets > 1 %>
              visiteurs
              <% else %>
              visiteur
            <% end %>
            <hr>
          </div>
          <div class="address-exhibit-dash">
          <strong> <%= @booking.exhibition.place %> </strong>
            <br>
          </div>
          <strong> <%= @booking.exhibition.address%> </strong>
          <div class="qrcode-dash">
            <%= image_tag("QRcode-utile.png", class: "logo-img") %>
          </div>
        </div>
      </div>
    </div>
  </div>
<!-- </div> -->