config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/dashboard", to: "pages#dashboard"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/dashboard", to: "pages#dashboard"
  resources :exhibitions, only: [:index, :show, :edit, :update, :destroy] do
    resources :bookings, only: [:index, :new, :create]
    resources :reviews, only: [:new, :create, :destroy]
    resources :favorites, only: [:create]
  end
  resources :favorites, only: [:destroy], as: "favorite_delete"
  resources :users do
    resources :friendships, only: [:new, :create, :index]
    resources :favorites, only: [:index]
  end
  resources :sites, only: [:show, :edit, :update, :destroy]
  get "/fav", to: "favorites#fav", as: "favorite"
  get "/ticket", to: "bookings#ticket", as: "ticket"
end

app/views/pages/dashboard.html.erb
<div class="banner-dashboard">
  <% if current_user.photo.attached? %>
    <%= cl_image_tag current_user.photo.key, class:"profile-pic-dashboard" %>
  <% else %>
    <i class="far fa-user profile-pic-dashboard"></i>
  <% end %>
  <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "btn btn-logout" %>
  <dir class= "welcome-message-banner">
    <div class="introduction">
      <h2>Hello, <%= current_user.first_name %></h2>
      <p>Bienvenue sur ton profil</p>
    </div>
  </dir>
</div>

<!-- width => 90, :height => 90, :crop => :thumb, :gravity => :face, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false -->

<div class="container">

  <ul class="tabs">
    <li data-tab-target="#bookings-content" class="active tab">Réservations</li>
    <li data-tab-target="#last-chance-content" class="tab">Dernière chance</li>
    <li data-tab-target="#recommandations-content" class="tab">Suggestions</li>
  </ul>


  <div class="class-content">
    <div id="bookings-content" data-tab-content class="active">
      <p class="header-tab">Tes visites à venir</p>
      <% i = 0 %>
        <% @bookings_futur.each do |booking| %>
        <% @booking = booking %>
        <div class="notification-group">
          <div class="notification">
            <img src= "<%= booking.exhibition.photo %>" class="avatar-large" />
            <div class="notification-content">
              <p><small>Réservation</small></p>
              <p><strong> <%= booking.exhibition.title %></strong></p>
              <p>Le <strong> <%= @booking.date.strftime('%d/%m/%Y')%> </strong>à <strong> <%= @booking.time.strftime('%H:%M') %> </strong></p>
              <p id="museum-description"><%= booking.exhibition.site.name %></p>
            </div>
            <div>
              <!-- <button type="button" id ='ticket-button' data-toggle="modal" data-target="#ticket-modal">
                Ticket
              </button> -->
              <button type="button" class="btn btn-infos-fav" data-toggle="modal" data-target="#ticketModal<%= i %>">
                Ticket
              </button>
            </div>
          </div>
        </div>
<%=render 'shared/ticket-modal', i:i %>
        <% i += 1 %>
      <% end %>

      <p class="header-tab">Tes visites passées</p>

      <% @bookings_passed.each do |booking| %>
        <%= link_to exhibition_path(booking.exhibition.id) do %>
          <div class="notification-group">
            <div class="notification">
              <img src= "<%= booking.exhibition.photo %>" class="avatar-large" />
              <div class="notification-content">
                <p><small>Visite passée</small></p>
                <p><strong> <%= booking.exhibition.title %></strong></p>
                <p>Le <strong><%= booking.date.strftime('%d/%m/%Y')%> </strong>à <strong> <%= booking.time.strftime('%H:%M') %> </strong></p>
                <p id="museum-description"><%= booking.exhibition.site.name %></p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>




    <div id="last-chance-content" data-tab-content>
      <p class="header-tab"></p>
      <p><%= current_user.first_name %>, ces expositions arrivent bientôt à leur terme ! Dépêche-toi :</p>

      <div class="block-notifications">
        <% @last_chance_exhibitions.each do |exhibition| %>
          <%= link_to exhibition_path(exhibition.id) do %>
            <div class="notification-group">
              <div class="notification">
                <img src= "<%= exhibition.photo %>" class="avatar-large" />
                <div class="notification-content">
                  <p><small>Jusqu'au <%= exhibition.ending_date.strftime('%d/%m/%Y') %></small></p>
                  <p><strong> <%= exhibition.title %></strong></p>
                  <p id="museum-description"><%= exhibition.site.name %></p>
                  <p id="museum-description"><%= exhibition.site.address %></p>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>



    <div id="recommandations-content" data-tab-content>
      <p class="header-tab"></p>
      <p>Ces expositions sont susceptibles de t'intéresser, jettes-y un coup d'oeil :</p>

      <div class="block-recommandations">
        <% @suggested_exhibitions.each do |exhibition| %>
          <%= link_to exhibition_path(exhibition.id) do %>
            <div class="card-product">
              <img src="<%= exhibition.photo %>" />
              <div class="card-product-infos">
                <h2><%= exhibition.title %></h2>
                <p> <%= exhibition.description %> </p>
              </div>
            </div>
          <% end %>
       <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner-home-page">
  <div class="banner-top">
    <%= image_tag("logo-museum-around-centered.png", class: "logo-img") %>
  </div>
  <div class='fingertips'>
    <h2>La culture à portée de main</h2>
  </div>

  <div class="search-bar">
    <%= simple_form_for :search, url: exhibitions_path, method: :get, class: "form-inline" do |f| %>
      <div class="magnifying-style-suite">
        <div class= "form-row justify-content-around" style="position:relative;">
      </div>
      <!-- <div class="magnifying-style">
        <i class="fas fa-search"></i>
      </div> -->
      <%= f.input :address, placeholder:'Où allons-nous ?', required: false, label: false, input_html: { id:"visit_address" }, class:"search-bar-address-input" %>
      </div>
    <%end%>
    <div class="geolocate-button-banner">
      <%= link_to exhibitions_path, class:"geolink" do %>
        <i class="fas fa-location-arrow pr-1"></i> À proximité
      <% end %>
    </div>
  </div>


  <div class="banner-b">
    <a class="banner-bottom" href="#section2">
    <br>
    <i class="fas fa-angle-down"></i></a>
  </div>
</div>


<div class="container text-center" id="section2">
  <div class="category-cards-box">

    <div class="cards">
      <div class="category-cards" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1543857778-c4a1a3e0b2eb?ixlib=rb-1.2.1&auto=format&fit=crop&w=706&q=80)">
        <%= link_to "Peinture", exhibitions_path(category: "Peinture"), class: "link-home-page" %>
      </div>

      <div class="category-cards" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1529154166925-574a0236a4f4?ixlib=rb-1.2.1&auto=format&fit=crop&w=967&q=80)">
        <%= link_to "Sculpture", exhibitions_path(category: "Sculpture"), class: "link-home-page" %>
      </div>

      <div class="category-cards" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1501435764075-903868ebb179?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80)">
        <%= link_to "Street Art", exhibitions_path(category: "Street-Art"), class: "link-home-page" %>
      </div>

      <div class="category-cards" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1518281181528-dfdb97a48e90?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTl8fGFyY2hpdGVjdHVyZSUyMG1vZGVybnxlbnwwfHwwfA%3D%3D&auto=format&fit=crop&w=800&q=60)">
        <%= link_to "Contemporain", exhibitions_path(category: "Contemporain"), class: "link-home-page" %>
      </div>

      <div class="category-cards" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1487837647815-bbc1f30cd0d2?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTZ8fHN0YWlyc3xlbnwwfHwwfA%3D%3D&auto=format&fit=crop&w=800&q=60)">
        <%= link_to "Design", exhibitions_path(category: "Design"), class: "link-home-page" %>
      </div>

      <div class="category-cards" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1587798074130-015f7eb202ed?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTR8fGFydCUyMGdhbGxlcnl8ZW58MHx8MHw%3D&auto=format&fit=crop&w=800&q=60)">
        <%= link_to "Photographie", exhibitions_path(category: "Photographie"), class: "link-home-page" %>
      </div>

      <div class="category-cards" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1487603097198-fe76cd44579d?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxzZWFyY2h8Mzh8fGFyY2hpdGVjdHVyZSUyMG1vZGVybnxlbnwwfHwwfA%3D%3D&auto=format&fit=crop&w=800&q=60)">
        <%= link_to "Architecture", exhibitions_path(category: "Architecture"), class: "link-home-page" %>
      </div>

      <div class="category-cards" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1440404653325-ab127d49abc1?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTF8fGNpbmVtYXxlbnwwfHwwfA%3D%3D&auto=format&fit=crop&w=800&q=60)">
        <%= link_to "Cinéma", exhibitions_path(category: "Cinema"), class: "link-home-page" %>
      </div>
<!--     </div>
 -->
<!--     <div class="cards" id="cards-bottom"> -->
      <div class="category-cards" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1592488881715-4bfcb5b7a911?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxzZWFyY2h8MzZ8fGhpc3Rvcnl8ZW58MHx8MHw%3D&auto=format&fit=crop&w=800&q=60)">
        <%= link_to "Histoire", exhibitions_path(category: "Historique"), class: "link-home-page" %>
      </div>

      <div class="category-cards" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1507838153414-b4b713384a76?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxzZWFyY2h8M3x8bXVzaWN8ZW58MHx8MHw%3D&auto=format&fit=crop&w=800&q=60)">
        <%= link_to "Musique", exhibitions_path(category: "Musique"), class: "link-home-page" %>
      </div>
    </div>
  </div>
</div>